--- 
author: ~
distribution_type: module
generated_by: Module::Install version 0.68
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: HTTP-Server-Simple
no_index: 
  directory: 
    - inc
    - t
requires: 
  CGI: 0
  Socket: 0
  Test::More: 0
  URI::Escape: 0
version: 0.31
